//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XoRisk_SelfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanReport
    {
        public int Id { get; set; }
        public string SystemIP { get; set; }
        public string SystemMAC { get; set; }
        public string ProjectCode { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string ScriptName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
